Changes to allow code to run on SparkFun OpenLog Artemis
bluerobotics/BlueRobotics_MS5837_Library pull request #22
Opened 2021-01-27 07:59 UTC by PaulZC

Hi @jaxxzer ,

We really like the BAR02 sensor and want to add support for it on [OpenLog Artemis](https://www.sparkfun.com/products/16832).
To do that, we need to remove the hardwiring to the ```Wire``` interface. This PR does that.

Please note: I haven't updated the version in library.properties. You might want to do that after merging.

Changes:
- Moved the .h and .cpp files into a **/src** folder
 - Change init to ```init(TwoWire &wirePort = Wire);```. wirePort is optional and will default to Wire so all existing code will continue to work normally
 - Add ```.begin``` which simply calls init
 - Add the first part of @NeilBaner 's PR #21 to allow the code to compile on Mbed platforms
 - Add a slightly different fix for the second part of #21 - changed the #defines to const uint8_t
 - Add keywords.txt
 - Add a second example - for the BAR02
 
I haven't included @senceryazici 's PR #16 to support the other OverSample Rates but his changes look good. You might want to merge those too.

Enjoy!

Paul

2021-02-03 16:12 UTC, patrickelectric requested changes
Hi @PaulZC! 
Thanks for the great contribution, it indeed is a great thing that you are doing!
Just some small corrections and a couple of suggestions to get it merged :)

2021-02-03 16:12 UTC, patrickelectric commented on src/MS5837.cpp
> +	_i2cPort = &wirePort; //Grab which port the user wants us to use
You could move _i2cPort from ptr to reference if you do the initialization of it in the constructor

2021-02-03 16:12 UTC, patrickelectric commented on src/MS5837.cpp
> +	else if (version == 0x15) // MS5837-02BA21
else unnecessary after return

2021-02-03 16:12 UTC, patrickelectric commented on src/MS5837.cpp
> +	else if (version == 0x1A) // MS5837-30BA26
You could also break it to a else case

2021-02-03 16:12 UTC, patrickelectric commented on src/MS5837.cpp
> +	_i2cPort->beginTransmission(MS5837_ADDR);
Check if i2cPort is not nullptr

2021-02-03 16:12 UTC, patrickelectric commented on src/MS5837.h
> +  bool begin(TwoWire &wirePort = Wire); // Calls init()
wrong indentation

2021-02-03 16:12 UTC, patrickelectric commented on src/MS5837.h
> +	uint8_t getModel(void);
void in constructor is unnecessary in C++ code

2021-02-04 07:53 UTC, PaulZC commented on src/MS5837.cpp
> +	_i2cPort = &wirePort; //Grab which port the user wants us to use
Yes, true, but we choose not to do it that way. All the SparkFun libraries accept the wirePort as an parameter in .begin. There are some devices that can communicate over both I2C or SPI and we deal with those by overloading .begin.

2021-02-04 07:55 UTC, PaulZC commented on src/MS5837.cpp
> +	else if (version == 0x15) // MS5837-02BA21
Sorry, I don't follow. This part of the code could be structured differently, a switch case might be more elegant, but the logic is sound.

2021-02-04 07:55 UTC, PaulZC commented on src/MS5837.cpp
> +	else if (version == 0x1A) // MS5837-30BA26
Yes, true. But the logic is sound.

2021-02-04 07:58 UTC, PaulZC commented on src/MS5837.cpp
> +	_i2cPort->beginTransmission(MS5837_ADDR);
Sure. OK. Resolved here:
https://github.com/bluerobotics/BlueRobotics_MS5837_Library/pull/22/commits/2b5747d7b7bf9c39e775cab5161cc7dc878f370b#diff-e98a2dd452878f22bfa9405f77a816ec8c6add4277c3d61c18ef3ed2a98ad598R91-R96

2021-02-04 07:59 UTC, PaulZC commented on src/MS5837.h
> +  bool begin(TwoWire &wirePort = Wire); // Calls init()
Pesky whitespace! Resolved here:
https://github.com/bluerobotics/BlueRobotics_MS5837_Library/commit/2b5747d7b7bf9c39e775cab5161cc7dc878f370b#diff-fedaeb63fea75cce65adad3c7c284f5f797befa455548788021315c68d0f423cR55

2021-02-04 08:00 UTC, PaulZC commented on src/MS5837.h
> +	uint8_t getModel(void);
OK. Resolved here:
https://github.com/bluerobotics/BlueRobotics_MS5837_Library/commit/2b5747d7b7bf9c39e775cab5161cc7dc878f370b#diff-fedaeb63fea75cce65adad3c7c284f5f797befa455548788021315c68d0f423cR61
and here:
https://github.com/bluerobotics/BlueRobotics_MS5837_Library/commit/2b5747d7b7bf9c39e775cab5161cc7dc878f370b#diff-e98a2dd452878f22bfa9405f77a816ec8c6add4277c3d61c18ef3ed2a98ad598R82

2021-02-04 08:01 UTC, PaulZC commented on src/MS5837.cpp
> +	return (init(wirePort));
Hi Patrick (@patrickelectric),
Thanks for the feedback!
We don't call Wire.begin inside the library. We expect the user to call Wire.begin externally. It saves problems with (e.g.) (re)setting the clock speed. Please see this post (scroll down to the **Don’t call Wire.begin() in the library** section).
https://www.sparkfun.com/news/3245
Yes, true, you could use a class constructor argument. We choose not to do it that way.
Paul

2021-02-05 10:56 UTC, PaulZC commented on src/MS5837.cpp
> +	else if (version == 0x15) // MS5837-02BA21
Ah, yes, you're right. I've changed this and have added more improvements in the latest commits:
- I've defined a const uint8_t for each sensor version (based on the values in the datasheets)
- I've added **MS5837_UNRECOGNISED** as a possible value for ```_model```
- ```.init``` sets ```_model``` according to the sensor version it extracts from PROM Word 0
- if the sensor version is unrecognised, ```.init``` still returns true but sets ```_model``` to **MS5837_UNRECOGNISED**
- the code is still backward-compatible. You can still call ```setModel``` to override ```_model``` if required. (E.g. if TE has used a different sensor version ID which they have forgotten to tell us about!)

The main reason I've added all of this is that we support the MS5637 on OpenLog Artemis. It has the same address as the MS5837 and has the same memory structure. It passes the same CRC test. Before I made these changes, the MS5837 was appearing as an MS5637. The MS5637 datasheet doesn't define what the 'sensor version' bits are, so I can't update the MS5637 library with the same changes... These changes mean I can test for an MS5837 first. If ```_model``` is **MS5837_UNRECOGNISED** the I know I'm almost certainly talking to a MS5637.

Anyway, I think we've ended up with a nice solution. Everything is backward-compatible. ```.init``` sets the ```_model``` automatically, but you can override it if you want to.

Cheers!

Paul

2021-02-05 10:57 UTC, PaulZC commented on src/MS5837.cpp
> +	else if (version == 0x1A) // MS5837-30BA26
Please see the comment above...

2021-02-08 13:32 UTC, patrickelectric commented
Hi @PaulZC, it appears that your PR is failing, can you rebase it over master branch ?

2021-02-08 14:19 UTC, PaulZC commented
Done!
Best wishes,
Paul

2021-02-17 21:05 UTC, PaulZC commented
Hi @patrickelectric ,
Are you able to merge this PR now?
Best wishes,
Paul

2021-03-02 20:25 UTC, jaxxzer commented
Bump @patrickelectric

2021-03-03 13:18 UTC, patrickelectric commented
Hi @PaulZC! 
I did the final tests and everything appears to be working, to avoid more work from your part, I did a couple of corrections and organization on the commit history, they are already on our master branch.
Thanks for you contribution and sorry for the delay!

2021-03-03 13:18 UTC, patrickelectric approved these changes
Merged manually.

2021-03-03 13:18 UTC, closed without merging

2021-03-03 13:33 UTC, PaulZC commented
No problem @patrickelectric (& @jaxxzer) - thank you!
All the best,
Paul